pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/RadovanVukovic/Docker/Container_API_GET_POST/GET_API'
            }
        }
        
        stage('Build') {
            steps {
                sh '''
                    docker build --tag image_api:latest .
                '''
            }
        }
        
        stage('Stop') {
            steps {
                sh '''
                    docker container stop api
                    docker container rm api
                '''
            }
        }
        
        stage('Deploy') {
            steps {
                sh '''
                    docker run --name api image_api:latest
                '''
            }
        }
        
    }
}
