apiVersion: v1
kind: Job
metadata:
  labels:
    app: My App
    type: API
  spec:
    containers:
      - name: api1
      image: image_for_api:latest
      command: ['python', 'test.py']
      restartPolicy: OnFailure